concourse-url: YOUR-CONCOURSE-SERVER-URL # e.g. http://192.168.100.4:8080/
concourse-team: TARGETED-CONCOURSE_TEAM  # e.g. main
concourse-username: CONCOURSE-USER-NAME  # e.g. admin
concourse-password: CONCOURSE-PASSWORD
concourse-pipeline-name: NAME-OF-YOUR-PIPELINE  # e.g. shipt-it-enhanced
github-access-token: YOUR-GIT-HUB-ACCESS-TOKEN
