resources:
- name: pipeline-scripts
  type: git
  source:
    branch: master
    uri: {{git-project-url}}

- name: PCF
  type: cf
  source:
    api: {{pcf-api}}
    organization: {{deploy-organization}}
    space: {{deploy-space}}
    username: {{deploy-username}}
    password: {{deploy-password}}
    skip_cert_check: true

jobs:
- name: prepare-and-deploy-nats-to-syslog
  serial: true
  public: true
  plan:
  - aggregate:
    - get: pipeline-scripts
      trigger: true
  - task: prep-manifest
    file: pipeline-scripts/pcf-monitoring/nats-to-syslog/ci/tasks/app-manifest-prep.yml
    params:
    params:
      NATS_USER_ID: {{nats_userid}}
      NATS_PASSWORD: {{nats_password}}
      NATS_IP: {{nats_ip}}
      NATS_PORT: {{nats_port}}
      NATS_SUBJECT: {{nats_subject}}
      SYSLOG_ENDPOINT: {{syslog_endpoint}}
  - put: PCF
    params:
      manifest: app-manifest-output/manifest.yml
      path: pipeline-scripts/pcf-monitoring/nats-to-syslog/app

# sample cf push command for nats-to-syslog app-build-output
# cf push nats-to-syslog -c './nats_to_syslog_linux_amd64 -nats-uri nats://nats:<nats password>@<nats-ip>:4222 -nats-subject ">" -syslog-endpoint <syslog-server>:514' --no-route -b binary_buildpack --health-check-type none -m 256M
