---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfservices/docker-concourse-cf-tools
    # insecure_registries: ["myregistry:443"]

inputs:
- name: pipeline-scripts

outputs:
- name: app-manifest-output

run:
  path: pipeline-scripts/pcf-monitoring/nats-to-syslog/ci/tasks/app-manifest-prep
