---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: "git"

inputs:
  - name: concourse-pipeline-samples

run:
  path: concourse-pipeline-samples/common/tasks/dummy-task.sh
