---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: "git"

run:
  path: sh
  args:
  - -exc
  - |
    echo "Placeholder task: do something here"
