---
resources:
- name: alpine-image-repo
  type: git
  source:
    uri: https://github.com/lsilvapvt/rootfs-alpine

- name: buildroot-git-image-repo
  type: git
  source:
    uri: https://github.com/lsilvapvt/rootfs-buildroot-git.git

jobs:
- name: Run-with-images-from-git
  plan:
  - get: alpine-image-repo
  - get: buildroot-git-image-repo
  - task: run-with-alpine-image-from-git
    image: alpine-image-repo
    config:
      platform: linux
      run:
        path: sh
        args:
        - -exc
        - |
          uname -mrs
          cat /etc/*-release
  - task: run-with-buildroot-image-from-git
    image: buildroot-git-image-repo
    config:
      platform: linux
      run:
        path: sh
        args:
        - -exc
        - |
          uname -mrs
          cat /etc/*-release
          git --version
